name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or the version you need

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # or the build command you use

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live # or the channel ID you want to deploy to

    env:
      REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      REACT_APP_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_MESSAGING_SEND_ID: ${{ secrets.FIREBASE_MESSAGING_SEND_ID }}
      REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      REACT_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
